"""add cascade delete to alerts

Revision ID: 037881a4e484
Revises: 0d6439d2e79f
Create Date: 2026-07-10 07:47:51.740997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '037881a4e484'
down_revision: Union[str, Sequence[str], None] = '0d6439d2e79f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('alerts_file_id_fkey'), 'alerts', type_='foreignkey')
    op.create_foreign_key(None, 'alerts', 'files', ['file_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.create_foreign_key(op.f('alerts_file_id_fkey'), 'alerts', 'files', ['file_id'], ['id'])
    # ### end Alembic commands ###
